name: test
on: workflow_dispatch
jobs:
  test:
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest, windows-latest]
        include:
        - os: ubuntu-latest
          path: ~/.cache/pip
        - os: macos-latest
          path: ~/Library/Caches/pip
        - os: windows-latest
          path: ~\AppData\Local\pip\Cache
    runs-on: ${{ matrix.os }}
    steps:
    - uses: actions/cache@v4
      with:
        path: ${{ matrix.path }}
        key: ${{ runner.os }}-pip-${{ hashFiles('**/requirements.txt') }}
        # restore-keys: |
        #  ${{ runner.os }}-pip-
    - name: cloning
      uses: actions/checkout@v4.2.2
    - name: add deps
      run: pip install -r requirements.txt
    - name: test
      run: pytest -v 
  
