name: Python version test
on:
  workflow_call:
    inputs:
      python-version:
        required: true
        type: string
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: cloning
        uses: actions/checkout@v4.2.2
      - name: install Python
        uses: actions/setup-python@v5
        with:
          python-version: ${{ inputs.python-version }}
      - name: add deps
        run: pip install -r requirements.txt
      - name: test
        run: pytest -vv

