name: test
on: workflow_dispatch
jobs:
  test:
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest, macos-latest, windows-latest]
        version: ["3.8", "3.9", "3.10", "3.11", "3.12", "3.13"]
    name: Python ${{ matrix.version }} ${{ matrix.os }}
        # include:
        # - os: ubuntu-latest
        #   path: ~/.cache/pip
        # - os: macos-latest
        #   path: ~/Library/Caches/pip
        # - os: windows-latest
        #   path: ~\AppData\Local\pip\Cache
    steps:
    # - uses: actions/cache@v4
    #   with:
    #     path: ${{ matrix.path }}
    #     key: ${{ runner.os }}-pip-${{ hashFiles('**/requirements.txt') }}
    - name: cloning
      uses: actions/checkout@v4.2.2
    - name: install Python
      uses: actions/setup-python@v5
      with:
        python-version: ${{ matrix.version }} 
        cache: 'pip' 
    - name: add deps
      run: pip install -r requirements.txt
    - name: test
      run: pytest -vv 
  
