name: test OS
on:
  push:
    branches:
      - master
  pull_request:
    types:
      - opened
jobs:
  test:
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: true
      matrix:
        os: [ubuntu-latest, macos-latest, windows-latest]
        version: ["3.11", "3.12", "3.13"]
        include:
          - os: ubuntu-latest
            path: ~/.cache/pip
          - os: macos-latest
            path: ~/Library/Caches/pip
          - os: windows-latest
            path: ~\AppData\Local\pip\Cache
    steps:
    - uses: actions/cache@v4
      with:
        path: ${{ matrix.path }}
        key: ${{ runner.os }}-pip-${{ hashFiles('**/requirements.txt') }}
        restore-keys: |
          ${{ runner.os }}-pip-
    - name: cloning
      uses: actions/checkout@v4.2.2
    - name: install Python
      uses: actions/setup-python@v5
      with:
        python-version: ${{ matrix.version }}
    - name: add deps
      run: pip install -r requirements.txt
    - name: test
      run: pytest -vv
