name: ubuntu-latest macos-latest windows-latest
on: push
jobs:
  test:
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: true
      matrix:
        os: [ubuntu-latest, macos-latest, windows-latest]
        version: "3.12"
    steps:
    - uses: actions/cache@v4
    - name: cloning
      uses: actions/checkout@v4.2.2
    - name: install Python
      uses: actions/setup-python@v5
      with:
        python-version: ${{ matrix.version }}
    - name: add deps
      run: pip install -r requirements.txt
    - name: test
      run: pytest -vv