name: python-3.11
on:
  push:
    branches:
      - master
  pull_request:
    types:
      - opened

jobs:
  ubuntu-latest:
    uses: ./.github/workflows/main.yml
    with:
      python-version: "3.11"
